# Устанавливаем базовый образ Python
FROM python:3.9-slim


# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы приложения
COPY central/api.py

# Устанавливаем рабочую директорию
WORKDIR /central

# Команда для запуска приложения
CMD ["python", "api.py"]
