# Устанавливаем базовый образ Python
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы приложения
COPY card_reader /card_reader

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /card_reader
USER appuser

# Устанавливаем рабочую директорию
WORKDIR /card_reader

# Команда для запуска приложения
CMD ["python", "api.py"]

