# Устанавливаем базовый образ Python
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы приложения
COPY connection /connection

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /connection
USER appuser

# Устанавливаем рабочую директорию
WORKDIR /connection

# Команда для запуска приложения
CMD ["python", "api.py"]
