FROM python:3.9

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY keyboard /keyboard
WORKDIR /keyboard


CMD ["python3", "keyboard.py"]