POST http://localhost:6000/ingest HTTP/1.1
content-type: application/json

[
    {
        "param_name": "current",
        "param_units": "A",
        "param_value": 80
    },
    {
        "param_name": "temperature",
        "param_units": "C",
        "param_value": 190
    }
]